name: cardioguard
description: "A flutter app for cardiac diagnosis."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.2.0
  shared_preferences: ^2.5.4
  sqflite: ^2.4.1
  path: ^1.9.1
  http: ^1.2.1
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.7+1
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

  windows:
    generate: true
    icon_size: 48 
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
